sudo: required
services:
  - docker

before_install:
  - docker build -t brucezwhub/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true brucezwhub/react-test npm test

after_success:
  - docker build -t brucezw/multi-client  ./client
  - docker build -t brucezw/multi-nginx  ./nginx
  - docker build -t brucezw/multi-server  ./server
  - docker build -t brucezw/multi-worker  ./worker 

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push brucezw/multi-client
  - docker push brucezw/multi-nginx
  - docker push brucezw/multi-server
  - docker push brucezw/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-653197568348'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY