sudo: required
services:
  - docker

before_install:
  - docker build -t brucezwhub/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true brucezwhub/react-test npm test

after_success:
  - docker build -t brucezwhub/multi-client  ./client
  - docker build -t brucezwhub/multi-nginx  ./nginx
  - docker build -t brucezwhub/multi-server  ./server
  - docker build -t brucezwhub/multi-worker  ./worker 
 #login into docker cli
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 #take those images and push them to docker hub
   - docker push brucezwhub/multi-client
   - docker push brucezwhub/multi-nginx
   - docker push brucezwhub/multi-server
   - docker push brucezwhub/multi-worker

#deploy:
#  provider: elasticbeanstalk  
  # region: "us-west-2"
  # app: "docker"
  # env: "Docker-env"
  # bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  # bucket_path: "docker"
  # on:
  #   branch: master
  # access_key_id: 
  #   secure: "$AWS_ACCESS_KEY"
  # secret_access_key:
  #   secure: "$AWS_SECRET_KEY"


