sudo: required
services:
  - docker

before_install:
  - docker build -t brucezwhub/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true brucezwhub/react-test npm test

after_success:
  - docker build -t brucezwhub/multi-client  ./client
  - docker build -t brucezwhub/multi-nginx  ./nginx
  - docker build -t brucezwhub/multi-server  ./server
  - docker build -t brucezwhub/multi-worker  ./worker 

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push brucezwhub/multi-client
  - docker push brucezwhub/multi-nginx
  - docker push brucezwhub/multi-server
  - docker push brucezwhub/multi-worker